services:
  notebook:
    build: .
    volumes:
      - ./experiments:/app/experiments
    ports:
      - "4000:4000"
    command: jupyter notebook --ip 0.0.0.0 --port 4000 --allow-root
    networks:
      - intelligent-system_default

networks:
  intelligent-system_default:
    external: true